# Generated by Django 4.2.7 on 2025-11-01 16:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('event_date', models.DateField()),
                ('location_name', models.CharField(max_length=500)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='WGS84 coordinates (Longitude, Latitude)', srid=4326)),
                ('significance', models.TextField()),
                ('category', models.CharField(choices=[('EASTER_RISING', 'Easter Rising (1916)'), ('WAR_INDEPENDENCE', 'War of Independence (1919-1921)'), ('TREATY', 'Treaty Period (1921-1922)'), ('CIVIL_WAR', 'Civil War (1922-1923)'), ('AFTERMATH', 'Aftermath & Establishment (1923+)')], max_length=50)),
                ('event_type', models.CharField(help_text='e.g., Battle, Ambush, Execution, Political', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('casualties', models.IntegerField(blank=True, null=True)),
                ('commanders', models.JSONField(blank=True, default=list, null=True)),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('sources', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Historical Site',
                'verbose_name_plural': 'Historical Sites',
                'ordering': ['event_date', 'name'],
                'indexes': [models.Index(fields=['event_date'], name='historical__event_d_19455d_idx'), models.Index(fields=['category'], name='historical__categor_341716_idx')],
            },
        ),
    ]
